export const UPDATE_TRACK_REQUEST = "UPDATE_TRACK_REQUEST";
export const UPDATE_TRACK_SUCCESS = "UPDATE_TRACK_SUCCESS";
export const UPDATE_TRACK_ERROR = "UPDATE_TRACK_ERROR";
export const UPDATE_TRACK_RESET = "UPDATE_TRACK_RESET";

export const TRACK_TO_UPDATE = "TRACK_TO_UPDATE";
