export const DELETE_TRACK_REQUEST = "DELETE_TRACK_REQUEST";
export const DELETE_TRACK_SUCCESS = "DELETE_TRACK_SUCCESS";
export const DELETE_TRACK_ERROR = "DELETE_TRACK_ERROR";
export const DELETE_TRACK_RESET = "DELETE_TRACK_RESET";
