export const FETCH_MY_SONG_REQUEST = "FETCH_MY_SONG_REQUEST";
export const FETCH_MY_SONG_SUCCESS = "FETCH_MY_SONG_SUCCESS";
export const FETCH_MY_SONG_ERROR = "FETCH_MY_SONG_ERROR";
export const FETCH_MY_SONG_RESET = "FETCH_MY_SONG_RESET";
