export const UPDATE_PLAYLIST_REQUEST = "UPDATE_PLAYLIST_REQUEST";
export const UPDATE_PLAYLIST_SUCCESS = "UPDATE_PLAYLIST_SUCCESS";
export const UPDATE_PLAYLIST_ERROR = "UPDATE_PLAYLIST_ERROR";
export const UPDATE_PLAYLIST_RESET = "UPDATE_PLAYLIST_RESET";
