export const UPDATE_SONG_REQUEST = "UPDATE_SONG_REQUEST";
export const UPDATE_SONG_SUCCESS = "UPDATE_SONG_SUCCESS";
export const UPDATE_SONG_ERROR = "UPDATE_SONG_ERROR";
export const UPDATE_SONG_RESET = "UPDATE_SONG_RESET";
