export const FETCH_SONG_REQUEST = "FETCH_SONG_REQUEST";
export const FETCH_SONG_SUCCESS = "FETCH_SONG_SUCCESS";
export const FETCH_SONG_ERROR = "FETCH_SONG_ERROR";
export const FETCH_SONG_RESET = "FETCH_SONG_RESET";

export const FETCH_SONG_BY_ID_REQUEST = "FETCH_SONG_BY_ID_REQUEST";
export const FETCH_SONG_BY_ID_SUCCESS = "FETCH_SONG_BY_ID_SUCCESS";
export const FETCH_SONG_BY_ID_ERROR = "FETCH_SONG_BY_ID_ERROR";
export const FETCH_SONG_BY_ID_RESET = "FETCH_SONG_BY_ID_RESET";

export const FETCH_ME_SONG_SUCCESS = "FETCH_ME_SONG_SUCCESS";

export const LIKE_SONG_REQUEST = "LIKE_SONG_REQUEST";
export const LIKE_SONG_SUCCESS = "LIKE_SONG_SUCCESS";
export const LIKE_SONG_ERROR = "LIKE_SONG_ERROR";
