export const FETCH_SONG_REQUEST = "FETCH_SONG_REQUEST";
export const FETCH_SONG_SUCCESS = "FETCH_SONG_SUCCESS";
export const FETCH_SONG_ERROR = "FETCH_SONG_ERROR";
export const FETCH_SONG_RESET = "FETCH_SONG_RESET";

export const PLAY_SONG = "PLAY_SONG";
